apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributed-app
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distributed-app
  template:
    metadata:
      labels:
        app: distributed-app
    spec:
      containers:
        - name: distributed-app
          image: distributed-app:1.3
          ports:
            - containerPort: 8080
