version: '3.8'

services:
  node1:
    build: .
    environment:
      - NODE_ID=1
      - NODE_HOST=127.0.0.1
      - NODE_PORT=8081
      - CLUSTER_NODES=127.0.0.1:8082,127.0.0.1:8083
    ports:
      - "8081:8081"

  node2:
    build: .
    environment:
      - NODE_ID=2
      - NODE_HOST=127.0.0.1
      - NODE_PORT=8082
      - CLUSTER_NODES=127.0.0.1:8081,127.0.0.1:8083
    ports:
      - "8082:8082"

  node3:
    build: .
    environment:
      - NODE_ID=3
      - NODE_HOST=127.0.0.1
      - NODE_PORT=8083
      - CLUSTER_NODES=127.0.0.1:8081,127.0.0.1:8082
    ports:
      - "8083:8083"
