version: '3.8'

networks:
  monitoring_network:
    driver: bridge

services:
  node1:
    build: .
    environment:
      - NODE_ID=1
      - NODE_HOST=127.0.0.1
      - NODE_PORT=8081
      - CLUSTER_NODES=127.0.0.1:8082,127.0.0.1:8083
      - ALGORITHM_TYPE=leader
    ports:
      - "8081:8081"
    networks:
      - monitoring_network


  node2:
    build: .
    environment:
      - NODE_ID=2
      - NODE_HOST=127.0.0.1
      - NODE_PORT=8082
      - CLUSTER_NODES=127.0.0.1:8081,127.0.0.1:8083
      - ALGORITHM_TYPE=broadcast
    ports:
      - "8082:8082"
    networks:
      - monitoring_network


  node3:
    build: .
    environment:
      - NODE_ID=3
      - NODE_HOST=127.0.0.1
      - NODE_PORT=8083
      - CLUSTER_NODES=127.0.0.1:8081,127.0.0.1:8082
      - ALGORITHM_TYPE=round-robin
    ports:
      - "8083:8083"
    networks:
      - monitoring_network


  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring_network


  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - monitoring_network


  aggregator:
    build: .
    environment:
      - NODE_ADDRESSES=http://node1:8081,http://node2:8082,http://node3:8083
    ports:
      - "8080:8080"  # Expose the dashboard
    networks:
      - monitoring_network