version: '3.8'

networks:
  monitoring_network:
    driver: bridge

services:
  node1:
    build: .
    environment:
      - NODE_ID=1
      - NODE_HOST=127.0.0.1
      - NODE_PORT=8081
      - CLUSTER_NODES=127.0.0.1:8082,127.0.0.1:8083
      - ALGORITHM_TYPE=leader
    ports:
      - "8081:8081"
    networks:
      - monitoring_network
    volumes:
      - ./logs:/var/log/app

  node2:
    build: .
    environment:
      - NODE_ID=2
      - NODE_HOST=127.0.0.1
      - NODE_PORT=8082
      - CLUSTER_NODES=127.0.0.1:8081,127.0.0.1:8083
      - ALGORITHM_TYPE=broadcast
    ports:
      - "8082:8082"
    networks:
      - monitoring_network
    volumes:
      - ./logs:/var/log/app

  node3:
    build: .
    environment:
      - NODE_ID=3
      - NODE_HOST=127.0.0.1
      - NODE_PORT=8083
      - CLUSTER_NODES=127.0.0.1:8081,127.0.0.1:8082
      - ALGORITHM_TYPE=round-robin
    ports:
      - "8083:8083"
    networks:
      - monitoring_network
    volumes:
      - ./logs:/var/log/app

  loki:
    image: grafana/loki:latest
    container_name: distributed-loki
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki-data:/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - monitoring_network
